# Generated by Django 5.1 on 2025-03-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('piket_from', models.IntegerField(blank=True, null=True)),
                ('piket_to', models.IntegerField(blank=True, null=True)),
                ('shoot_date_from', models.DateField(blank=True, null=True)),
                ('shoot_date_to', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('kml_file_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='новая', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orthophoto', models.BooleanField(default=False)),
                ('laser', models.BooleanField(default=False)),
                ('panorama', models.BooleanField(default=False)),
                ('overview', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'object_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.user')),
                ('flight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main_app.flightrequest')),
            ],
            options={
                'db_table': 'request_history',
                'managed': True,
            },
        ),
    ]
