# Generated by Django 5.1 on 2025-04-02 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FlightResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('ortho', 'Ортофотоплан'), ('laser', 'Лазерное сканирование'), ('panorama', 'Панорама'), ('overview', 'Обзорные фото')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='flight_results/')),
                ('view_link', models.URLField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('flight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_files', to='main_app.flightrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TempResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='temp_uploads/')),
                ('view_link', models.URLField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
